### ISSUE TITLE
Interface inconsistency when selecting framework

### ISSUE THREAD

**Issue by djadomi** [Melkeydev/go-blueprint#116]
When selecting the framework, moving up and down the list, then selecting with space marks that framework with a check. But if I move up or down from that framework, without marking any other framework with space, the framework that is focused (not checked) will be used when pressing 'y' to continue.

<img width="997" alt="image" src="https://github.com/Melkeydev/go-blueprint/assets/512513/b5cd708c-e27a-4e48-ae11-046571b01e58">

**Comment by jcsmurph** [comment]
The issue seems to be that the Update function in cmd/ui/multiInput/multiInput.go updates the choice with the cursor position rather than the selected:

![image](https://github.com/Melkeydev/go-blueprint/assets/26413825/b02cedc4-4787-44e3-8f5e-bab3ef7cd8dc)

I am new to Golang so there is probably a better way to get the value of the key from the selected choice. But this seems to have fixed it:

![image](https://github.com/Melkeydev/go-blueprint/assets/26413825/148f0c67-c23e-4cdf-893b-e9b228b59667)

![image](https://github.com/Melkeydev/go-blueprint/assets/26413825/f36ff4e6-2bbb-4a87-8f4f-6675efb819c0)

**Comment by jcsmurph** [comment]
Not sure why I didn't think of just passing the key as a value in a loop. Long day yesterday.
