### ISSUE TITLE
[Feature Request]  Remove .env and add .env to .gitignore

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#140]
### Tell us about your feature request

Since we are adding .env.example we no longer need a .env file and additionally we should include this as one of the files to ignore

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
@Melkeydev 

I don't think it's a good idea to remove the .env file completely. It is a two-part file, created from globalenv.tmpl and a specific DB template. Maybe we can remove the DB-specific variables. If we keep the current configuration, that's good, or alternatively, we could remove the .env.example and bind default variables in .env so that Docker Compose works out of the box.

What do you think is the best approach?

```
#global 
PORT=8080
APP_ENV=local 

#DB specific
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
DB_ROOT_PASSWORD=
```
