### ISSUE TITLE
[Feature Request] Add option to include slashes and dots in project name

### ISSUE THREAD

**Issue by wojcraft** [Melkeydev/go-blueprint#285]
### Tell us about your feature request

It's not possible to enter project name as this: `github.com/wojcraft/project-name` - I've got used to this naming for learning and I see it also affects imports. Can you help me with that?

Here is screenshot of a input that needs to be modified in order to solve this request
![image](https://github.com/user-attachments/assets/29c29726-03c4-442f-a2aa-d9ffee1975c4)

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
You are right, it is not possible to use '/' as input in the project name. If the go-blueprint create -n github.com/user/project-name command is executed, the CLI would create subdirectories after '/'. Thanks for addressing this....it needs to be fixed.

**Comment by Ujstor** [comment]
This is an easy fix, the only thing that needs to be changed is the regex in the sanitizeInput() function (textinput.go):

```go
func sanitizeInput(input string) error {
	matched, err := regexp.Match("^[a-zA-Z0-9_\\-\\./]+$", []byte(input))
	if !matched {
		return fmt.Errorf("string violates the input regex pattern, err: %v", err)
	}
	return nil
}
```

**Comment by wojcraft** [comment]
> This is an easy fix, the only thing that needs to be changed is the regex in the sanitizeInput() function (textinput.go):
> 
> ```go
> func sanitizeInput(input string) error {
> 	matched, err := regexp.Match("^[a-zA-Z0-9_\\-\\./]+$", []byte(input))
> 	if !matched {
> 		return fmt.Errorf("string violates the input regex pattern, err: %v", err)
> 	}
> 	return nil
> }
> ```

> /^[a-zA-Z0-9_\\-\\.\/]+$
I rather meant to make dots and slashes available at the same time. To allow urls like github.com/wojcraft/test

**Comment by Ujstor** [comment]
I agree...I did just a quick test.

**Comment by H0llyW00dzZ** [comment]
Wait, I think you don't have to explicitly use a regex because it's a byte.

**Comment by wojcraft** [comment]
Dear @Ujstor,

So, are you going to implement this feature? I feel a little disoriented looking at this issue, so I'm just asking about a status of it.

If you want to know more details about what I mean in this quite small Feature Request, just let me know!

All the best!
Wojcraft

**Comment by Ujstor** [comment]
The issue is open, and anyone can solve it and submit a PR :)

**Comment by Patel-Raj** [comment]
If the project name entered is "github.com/wojcraft/project-name", could you please suggest what should be the expected behavior from 1 or 2? 

Behavior 1:
root folder name: project-name
module name: github.com/wojcraft/project-name

Behavior 2:
root folder name: github.com/wojcraft/project-name
module name: github.com/wojcraft/project-name

If behavior 2 is expected, than is it possible on Linux based operating systems to have / in directory name?

**Comment by Ujstor** [comment]
@Patel-Raj 
I think option number 1 would be best to implement because of cross-platform compatibility:
root folder name: project-name
module name: github.com/wojcraft/project-name

Behavior 2 is what you get if we change the sanitizeInput function and allow . and /. In this case, the blueprint’s default behavior will create a directory tree github.com/wojcraft/project-name. As you pointed out, on Windows, this will be a big issue.

@H0llyW00dzZ This is why regex is used, not just a plain string.

**Comment by H0llyW00dzZ** [comment]
> @Patel-Raj I think option number 1 would be best to implement because of cross-platform compatibility: root folder name: project-name module name: github.com/wojcraft/project-name
> 
> Behavior 2 is what you get if we change the sanitizeInput function and allow . and /. In this case, the blueprint’s default behavior will create a directory tree github.com/wojcraft/project-name. As you pointed out, on Windows, this will be a big issue.
> 
> @H0llyW00dzZ This is why regex is used, not just a plain string.

It can be more easily achieved using the URL builder from the standard library and removing the scheme (http/https) instead of using regex.

for example:

```go
func sanitizeInput(input string) error {
	// Remove the URL scheme (e.g., http://, https://) from the input
	input = strings.TrimPrefix(strings.TrimPrefix(input, "https://"), "http://")

	_, err := url.Parse("//" + input)
	if err != nil {
		return fmt.Errorf("invalid input: %v", err)
	}
	return nil
}
```
