### ISSUE TITLE
Cursor not visible when go-blueprint create fails

### ISSUE THREAD

**Issue by beeploop** [Melkeydev/go-blueprint#315]
### What is the problem?

I can't see my cursor whenever an error occur during go-blueprint create. I can still type but the cursor is invisible.

### Operating System

Pop OS

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

Run go-blueprint create with unreliable or without internet connection.

**Comment by Ujstor** [comment]
It is an old bug that slipped in when the Spinner was implemented. The Spinner is running in a separate goroutine, and if an error occurs, the terminal gets captured, and there is no visible input. We thought the bug was resolved, but obviously it isn't.

Feel free to let me know if anyone is interested in working on resolving this issue.

**Comment by vinitparekh17** [comment]
@Ujstor i would like to pick this up

**Comment by Ujstor** [comment]
Resolved in #318
