### ISSUE TITLE
Bug: The non-interactive command from tip message is broken

### ISSUE THREAD

**Issue by basokant** [Melkeydev/go-blueprint#73]
Bug introduced in #59 (I messed up team).
Remind me not to code at 4am. Also we very much need unit tests.

- [x] include `create` in command
- [x] fix `standard library` framework option to be `standard-library` instead.

<img width="766" alt="image" src="https://github.com/Melkeydev/go-blueprint/assets/70033855/4d8ba738-abe1-4666-9a06-183d06ce7401">

**Comment by nickwarters** [comment]
Suggest removing the `--name` flag from the tip message as running the command with it would result in a failure as the directory would already exist (if still in the same directory). If moving to another path and running the command, you'd be more likely to change the name rather than use the same one. 

Thoughts on this @basokant ?

**Comment by basokant** [comment]
agreed, will add this to my PR as well. planning on getting valid flag values #61 in one PR as well.
